name: best_baltanem
description: Flutter best_practices bal_tanem
version: 0.1.3
homepage: https://github.com/HalilUcel14/best_baltanem
# author: Halil Ucel <hucelsoft@gmail.com> <https://www.youtube.com/channel/UC4GTOIiDWEe6jIuXlqSIhQg>
# author: Halil Ücel


environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  #-#-#-# Kartal packages
  device_info: ^2.0.0
  diacritic: ^0.1.3
  flutter_lints: ^1.0.4
  mask_text_input_formatter: ^2.0.0
  mime: ^1.0.0
  package_info_plus: ^1.4.0
  share: ^2.0.0
  url_launcher: ^6.0.1
  #-#-#-#

  # animation
  animations: ^2.0.2
  #
  # image management
  flutter_svg: ^1.0.3
  #
  # state management
  provider: ^6.0.2
  mobx: ^2.0.6+1
  mobx_codegen: ^2.0.5+2
  #


dev_dependencies:
  build_runner: ^2.1.8
  flutter_test:
    sdk: flutter
  
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
